# Generated by Django 2.0.7 on 2018-11-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0002_tests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tests',
        ),
    ]
