# Generated by Django 2.0.7 on 2018-11-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0003_delete_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='password',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mail',
            name='receiver',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sender',
            field=models.EmailField(max_length=50),
        ),
    ]
