# Generated by Django 2.0.7 on 2018-11-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0005_auto_20181114_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=50)),
                ('send_mode', models.CharField(max_length=50)),
                ('receiver', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
