# Generated by Django 2.0.7 on 2018-11-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0006_send_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send_rules',
            name='receiver',
        ),
    ]
